---
title: "hw6"
format: html
output-file: "index"
---

### Exercise 1

a.  What is the most interesting lesson, guide, or piece of advice Tufte offers you in this chapter?

b.  Tufte shares some of his favorite graphics in this chapter. Pick one (but not the one about the military advance on and retreat from Russia) and answer the following.

    -   What page is your graphic on? \[Take a screen shot and include the image as well, if you can.\]

    -   Why did you pick the graphic you chose?

    -   What encoding channels are used in the graphic? What variables are they associated with?

    -   What, if any, elements of the graphic would be hard/impossible for you to implement in Vega-Lite (given what we know so far)?

    -   What point is Tufte illustrating with this graphic?

### Exercise 2

List one or two ideas that you learned in these sections that will change the way you design and create data graphics.

### Exercise 3

```{r}
"data":
    { "values" :
        [{"Date":"Q1-2017","Completion Rate":0.91,"Response Rate":0.023},
        {"Date":"Q2-2017","Completion Rate":0.93,"Response Rate":0.018},
        {"Date":"Q3-2017","Completion Rate":0.91,"Response Rate":0.028},
        {"Date":"Q4-2017","Completion Rate":0.89,"Response Rate":0.023},
        {"Date":"Q1-2018","Completion Rate":0.84,"Response Rate":0.034},
        {"Date":"Q2-2018","Completion Rate":0.88,"Response Rate":0.027},
        {"Date":"Q3-2018","Completion Rate":0.91,"Response Rate":0.026},
        {"Date":"Q4-2018","Completion Rate":0.87,"Response Rate":0.039},
        {"Date":"Q1-2019","Completion Rate":0.83,"Response Rate":0.028}] 
    }
```
